# fly.toml app configuration file generated for juicefs-fly on 2024-06-06T16:41:00-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'juicefs-fly'
primary_region = 'ord'

[env]

[http_service]
internal_port = 11434      # change me to 11434!
force_https = false        # change mo to false!
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[mounts]
source = "juicefs_cache"
destination = "/var/jfsCache"

[[vm]]
size = "a100-40gb"
